INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_GNURADIO_DIGITAL gnuradio-digital>=3.7)

FIND_PATH(
    GNURADIO_DIGITAL_INCLUDE_DIRS
    NAMES gnuradio/digital/api.h
    HINTS $ENV{GNURADIO_DIGITAL_DIR}/include
        ${PC_GNURADIO_DIGITAL_INCLUDEDIR}
    PATHS /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GNURADIO_DIGITAL_LIBRARIES
    NAMES gnuradio-digital
    HINTS $ENV{GNURADIO_DIGITAL_DIR}/lib
        ${PC_GNURADIO_DIGITAL_LIBDIR}
    PATHS /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GNURADIO_DIGITAL DEFAULT_MSG GNURADIO_DIGITAL_LIBRARIES GNURADIO_DIGITAL_INCLUDE_DIRS)
MARK_AS_ADVANCED(GNURADIO_DIGITAL_LIBRARIES GNURADIO_DIGITAL_INCLUDE_DIRS)
