INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_GNURADIO_ANALOG gnuradio-analog>=3.7)

FIND_PATH(
    GNURADIO_ANALOG_INCLUDE_DIRS
    NAMES gnuradio/analog/api.h
    HINTS $ENV{GNURADIO_ANALOG_DIR}/include
        ${PC_GNURADIO_ANALOG_INCLUDEDIR}
    PATHS /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GNURADIO_ANALOG_LIBRARIES
    NAMES gnuradio-analog
    HINTS $ENV{GNURADIO_ANALOG_DIR}/lib
        ${PC_GNURADIO_ANALOG_LIBDIR}
    PATHS /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GNURADIO_ANALOG DEFAULT_MSG GNURADIO_ANALOG_LIBRARIES GNURADIO_ANALOG_INCLUDE_DIRS)
MARK_AS_ADVANCED(GNURADIO_ANALOG_LIBRARIES GNURADIO_ANALOG_INCLUDE_DIRS)
